#!/usr/bin/env bash
# Run a .3dsx in Azahar and print the title's own output.
#
#   ./scripts/run-in-azahar.sh build-3ds/phase0_3ds.3dsx [seconds]
#
# Titles log via ctr_log.h, which routes stderr through svcOutputDebugString.
# Azahar records that as `Debug.Emulated <Debug>` in its log file, so this
# extracts those lines and nothing else — which makes emulator runs usable in
# scripts rather than something you have to watch.
#
# Requires log_filter to include Debug.Emulated:Debug in Azahar's qt-config.ini;
# this script sets it if missing.
set -euo pipefail

ROM="${1:?usage: run-in-azahar.sh <file.3dsx> [seconds]}"
SECS="${2:-20}"
AZAHAR="${AZAHAR:-/tmp/azahar.AppImage}"
CONFIG="$HOME/.config/azahar-emu/qt-config.ini"
LOG="$HOME/.local/share/azahar-emu/log/azahar_log.txt"

[ -x "$AZAHAR" ] || { echo "Azahar not found at $AZAHAR (set \$AZAHAR)"; exit 1; }
[ -f "$ROM" ] || { echo "no such ROM: $ROM"; exit 1; }

# Debug.Emulated logs below Info, so the stock filter hides the title's output.
if [ -f "$CONFIG" ] && ! grep -q "Debug.Emulated:Debug" "$CONFIG"; then
    cp "$CONFIG" "$CONFIG.bak-soh3ds"
    sed -i 's|^log_filter=.*|log_filter=*:Info Debug.Emulated:Debug|; s|^log_filter\\default=.*|log_filter\\default=false|' "$CONFIG"
    echo "(enabled Debug.Emulated logging; original saved as $(basename "$CONFIG").bak-soh3ds)"
fi

# Two runs would otherwise race: Azahar keeps one log per user-dir and rotates
# it on launch, so a concurrent run silently overwrites the other's output.
# Serialise on a lock instead, and never touch an emulator this script did not
# start - a blanket pkill would take out the user's own sessions too.
LOCK="${TMPDIR:-/tmp}/soh3ds-azahar.lock"
exec 9>"$LOCK"
if ! flock -w 600 9; then
    echo "timed out waiting for another emulator run to finish"; exit 1
fi

# Azahar rotates its log on every launch (previous run -> azahar_log.old.txt),
# so under the lock the current file contains exactly this run.
# SOH3DS_MOVIE injects input from an Azahar TAS movie, the only route available
# here - there is no xdotool/ydotool to press a key with.
#
# It must be a *recorded* movie (-r), not a synthesised one. Azahar consumes one
# 7-byte ControllerState per handler call from a single stream, and a type
# mismatch consumes the state and skips it rather than resyncing. A run of this
# title consumes three types - PadAndCircle and Touch strictly paired by
# Module::UpdatePadCallback, plus IrRst on its own independent timer (measured
# 2990 : 2990 : 2534 over one run). Because IrRst is not phase-locked to the pad
# updates, no statically generated byte sequence can stay in sync: a hand-built
# [Pad, Touch] stream desynchronises within the first few updates and every
# later pad state lands on the wrong handler.
#
# Accelerometer and Gyroscope never appear, confirming those events are only
# scheduled when the sensors are enabled, which OoT does not do.
MOVIE_ARGS=()
# SOH3DS_VIDEO dumps the emulator's composited output to a file, which is the
# only way to actually see whether the top screen renders - the title's own
# logging can only say that draw calls were issued.
if [ -n "${SOH3DS_VIDEO:-}" ]; then
    MOVIE_ARGS+=(-d "$SOH3DS_VIDEO")
    echo "(dumping video to $(basename "$SOH3DS_VIDEO"))"
fi
if [ -n "${SOH3DS_MOVIE:-}" ]; then
    [ -f "$SOH3DS_MOVIE" ] || { echo "no such movie: $SOH3DS_MOVIE"; exit 1; }
    # Short form only: this AppImage's parser rejects --movie-play with
    # "invalid option -- '-'", so -p is the confirmed accepted spelling.
    MOVIE_ARGS+=(-p "$SOH3DS_MOVIE")
    echo "(injecting input from $(basename "$SOH3DS_MOVIE"))"
fi
QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-xcb}" setsid "$AZAHAR" "${MOVIE_ARGS[@]}" "$ROM" >/dev/null 2>&1 &
AZ_PID=$!
# Detach from job control so the shell does not print "Killed" when we stop it.
disown "$AZ_PID" 2>/dev/null || true

# Kill only our own process group, however we leave.
GRACE=1
[ -n "${SOH3DS_VIDEO:-}" ] && GRACE=${SOH3DS_VIDEO_GRACE:-30}
cleanup() {
    kill -TERM -"$AZ_PID" 2>/dev/null || kill -TERM "$AZ_PID" 2>/dev/null || true
    # Wait for a clean exit before forcing it. Killing early truncates a video
    # dump, whose container trailer is only written during shutdown.
    for _ in $(seq 1 "$GRACE"); do
        kill -0 "$AZ_PID" 2>/dev/null || break
        sleep 1
    done
    kill -KILL -"$AZ_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

sleep "$SECS"
cleanup
trap - EXIT INT TERM
sleep 1

echo "--- title output ---"
grep -oP '(?<=OutputDebugString:\d{1,6}: ).*' "$LOG" 2>/dev/null \
    || echo "(none — did the title hang before its first log?)"

echo "--- emulator errors ---"
grep -E "<Error>|<Critical>" "$LOG" 2>/dev/null \
    | grep -viE "ClCertA|Delay generator|title id for ROM" \
    | sed -E 's/.*(unimplemented function [^:]*|<Critical>.*)/\1/' | sort -u | head -10 || true
